### ISSUE TITLE
opt-in analytics question not shown on second install

### ISSUE THREAD

**Issue by sethladd** [google/stagehand#147]
Following these steps:

```
pub global deactivate stagehand
rm ~/.stagehand
pub global activate stagehand
stagehand webapp
```

Does not show the opt-in question to the user. I would imagine it should, as I've explicitly deleted the `.stagehand` file.

**Comment by seaneagan** [comment]
Could use the [stdioType](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:io#id_stdioType) to detect whether a prompt makes sense... if not for [this bug](http://dartbug.com/21821) :(.

**Comment by seaneagan** [comment]
I think it's better to prompt on the first invocation of `stagehand <generator>` than on `stagehand` or `stagehand --help`, since the user may never even run the latter while using the tool.

I ran into this when working on #211, since unscripted doesn't support running arbitrary code for --help, since that's not a common thing to do.
