### ISSUE TITLE
Have an initial IntelliJ launch configuration for Web Applications

### ISSUE THREAD

**Issue by jwren** [google/stagehand#389]

**Comment by kwalrath** [comment]
Can you give some more details on what this means?

**Comment by chalin** [comment]
@kevmoo - any opinion about this?

Launching a web app isn't very involved -- select index.html and then "Run...". These are the steps that we ask users to perform in our Angular docs. Is it really worth adding a launch config for this?

I'm concerned that we might then end up having to add launch configurations for all templates, for IntelliJ and potentially other editors.

Jaime: was there more to the launch config that you wanted to add?

**Comment by devoncarew** [comment]
For some context on this, we have a goal for improving the getting started experience for Dart web apps in Q2, and associated with that, streamlining the run/debug experience.

We may add IntelliJ launch configs to other templates, but there are no plan to do so now.

We won't be adding launch configs for any other editors - we're only looking to streamline the IntelliJ / WebStorm experience here.

Another item we've encountered in UX reviews is there are are too many new project templates now - there's too much choice for the user and not enough clarity on which is the 'right' template. It was always a goal of stagehand to be proscriptive - to have a few high quality templates rather than supporting many different project types and configurations. I'll file a separate issue, but we'll likely need to drop a few templates and have clearer guidelines about when new ones are added.

**Comment by alexander-doroshko** [comment]
Not sure what this request is about. The Dart plugin itself already creates a ready-to-use run configuration for `web/index.html` file after creating any web project using stagehand. And in case of command-line app IDE generates corresponding Dart Command Line App run configuration. Link to the corresponding code: https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/projectWizard/DartProjectTemplate.java#L101

If anything could be done better we can do it at Dart plugin end. I don't think stagehand has to generate IDE-specific files.
