### ISSUE TITLE
Add a default favicon to AngularDart projects

### ISSUE THREAD

**Issue by matanlurey** [google/stagehand#418]
![favicon](https://cloud.githubusercontent.com/assets/168174/26525015/8bdbf6e6-42fd-11e7-8930-450d45ef1fb8.png)

This avoids a 404 when web browsers try to download one for new users.

Also needed in `.html`:

```html
<link rel="icon" type="image/png" href="favicon.png">
```

(We might want to do the same with the Dart logo for the non-Angular examples)

**Comment by chalin** [comment]
#427 adds a favicon link like this:
```html
<link rel="shortcut icon" type="image/png" href="favicon.png">
```
Notice the use of `rel="shortcut icon"` vs. Matan's original suggestion of `rel="icon"`.

But, according to this [MDN page on Link types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types):
> The shortcut link type is often seen before icon, but this link type is non-conforming, ignored and **web authors must not use it anymore**.

Reopening this issue so that it can be fixed in the `web-simple` and `web-angular` templates. If y'all feel that this is unnecessary, let me know or just close the issue once again.

**Comment by devoncarew** [comment]
@chalin, perhaps track the change in a separate issue?

**Comment by chalin** [comment]
Sure, though here is the followup PR: #434.
